### ISSUE TITLE
Delete repo if not being used

### ISSUE THREAD

**Issue by stevemar** [IBM/CustomPac#1]
@OldNavi it appears this repo is not being used, please delete it if that's the case

**Comment by v1gnesh** [comment]
Nooo, let it stay!

**Comment by stevemar** [comment]
Well, 2 years (April 2022) after reporting the issue (March 2020), it looks like the repo is no longer empty. I'll close this issue as it's no longer applicable.

**Comment by krook** [comment]
+1 from me to let it live @stevemar 😺
